### ISSUE TITLE
Github Actions Runner

### ISSUE THREAD

**Issue by jahvon** [jahvon/flow#136]
Implement a container image and configurations for a flow-backed GitHub Actions runner. The runner would take a workspace repository and a list of flow executables to run from that workspace, enabling CI/CD workflows to be defined using flow's executable system.

## Example Usage

```yaml
# .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jahvon/flow-runner@v1
        with:
          workspace-repo: ${{ github.repository }}
          executables: |
            - validate
            - build binary
            - run tests
          secrets: |
            vault-key: ${{ secrets.VAULT_KEY }}
```
