### ISSUE TITLE
Request executable type

### ISSUE THREAD

**Issue by jahvon** [jahvon/flow#25]
### Enhancement Summary

The ability to define REST API request in YAML. 

#### Feature list

- [ ] Accepts HTTP method (GET, POST, DELETE, etc)
- [ ] Accepts request headers
- [ ] Include parameter values in request headers
- [ ] Accepts expected response type; validate response
- [ ] Accepts expected status code
- [ ] Configure pretty json output
- [ ] Configure json -> table output
- [ ] Filter / modify response with jq
- [ ] Save response output to file

#### Config mockups

```yaml
  - type: request
    name: get-todo
    timeout: 5s
    spec:
      url: https://jsonplaceholder.typicode.com/todos/1
      method: GET
      headers:
        "Content-Type": "application/json"
        "Authorization": "secret:authorization_token"
      print: .title
      save:
        from: .title
        to: title.json
```
