### ISSUE TITLE
Parallel executable type

### ISSUE THREAD

**Issue by jahvon** [jahvon/flow#26]
### Enhancement Summary

Execute multiple executables in parallel go routines.

#### Feature list

- [ ] Any executable type can be configured to run as parallel. Framework should be allow adding new executables with minimal to no setup.
- [ ] CLI command grouped with / included in the `start` command (e.g. `flow start ...`)

#### Config mockups

```yaml
  - type: start/parallel # run executable sub type
    name: setupk8s
    description: open and initialize for Kubernetes development
    spec:
      open: dev:vscode
      run: k8s:initCluster
      start/sequence: run img:build, run img:push
      request: k8s:pollReady
```
