### ISSUE TITLE
Sequence executable type

### ISSUE THREAD

**Issue by jahvon** [jahvon/flow#27]
### Enhancement Summary

Run a list of executables in an ordered sequence. 

#### Feature List

- [ ] Any executable type can be configured to run in sequence. Framework should be allow adding new executables with minimal to no setup.
- [ ] CLI command grouped with / included in the start command (e.g. flow start ...)

#### Config mockups

```yaml
 - type: start/sequence # start executable sub type
    name: randomResearchSession
    aliases:
      - rrs
    description: prepare desktop for a random research session
    spec:
      start/parallel: open apps:brave, open apps:obsidian
      request: learning:fetchResearchTopic
      run: learning:printResearchSessionGuide
```
