### ISSUE TITLE
Collapse `type` exec definition field

### ISSUE THREAD

**Issue by jahvon** [jahvon/flow#64]
### Enhancement Summary

The `type` key is kind of unnecessary. An exec defined as:

```
  - verb: setup
    name: drive-mount
    tags:
      - linux
    description: Mount a drive on the local machine
    spec:
      type:
        exec:
          file: //scripts/mount-drive.sh
```

Can be simplified to 
```
  - verb: setup
    name: drive-mount
    tags:
      - linux
    description: Mount a drive on the local machine
    spec:
      exec:
        file: //scripts/mount-drive.sh
```

Better yet, if `spec` can be dropped, that would simplify things even more
```
  - verb: setup
    name: drive-mount
    tags:
      - linux
    description: Mount a drive on the local machine
    exec:
      file: //scripts/mount-drive.sh
```

### Additional context

Need to play around with yaml tags and structs
